# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_msg.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fimage_msg.proto\":\n\x0b\x43loudPoints\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"3\n\tLidarScan\x12\x12\n\x06\x61ngles\x18\x07 \x03(\x02\x42\x02\x10\x01\x12\x12\n\x06ranges\x18\x08 \x03(\x02\x42\x02\x10\x01\"-\n\x06Pose2D\x12\t\n\x01x\x18\x04 \x01(\x02\x12\t\n\x01y\x18\x05 \x01(\x02\x12\r\n\x05theta\x18\x06 \x01(\x02\"Z\n\tLidarData\x12\x18\n\x04scan\x18\n \x01(\x0b\x32\n.LidarScan\x12\x1c\n\x06points\x18\x0b \x01(\x0b\x32\x0c.CloudPoints\x12\x15\n\x04pose\x18\x0c \x01(\x0b\x32\x07.Pose2D27\n\x0fPointsProcessor\x12$\n\x0bgetLocation\x12\n.LidarData\x1a\x07.Pose2D\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_msg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIDARSCAN'].fields_by_name['angles']._loaded_options = None
  _globals['_LIDARSCAN'].fields_by_name['angles']._serialized_options = b'\020\001'
  _globals['_LIDARSCAN'].fields_by_name['ranges']._loaded_options = None
  _globals['_LIDARSCAN'].fields_by_name['ranges']._serialized_options = b'\020\001'
  _globals['_CLOUDPOINTS']._serialized_start=19
  _globals['_CLOUDPOINTS']._serialized_end=77
  _globals['_LIDARSCAN']._serialized_start=79
  _globals['_LIDARSCAN']._serialized_end=130
  _globals['_POSE2D']._serialized_start=132
  _globals['_POSE2D']._serialized_end=177
  _globals['_LIDARDATA']._serialized_start=179
  _globals['_LIDARDATA']._serialized_end=269
  _globals['_POINTSPROCESSOR']._serialized_start=271
  _globals['_POINTSPROCESSOR']._serialized_end=326
# @@protoc_insertion_point(module_scope)
