# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"4\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\" \n\x04Vels\x12\x0b\n\x03v_l\x18\x04 \x01(\x02\x12\x0b\n\x03v_r\x18\x05 \x01(\x02\"-\n\x04\x44\x61ta\x12\x10\n\x01v\x18\n \x01(\x0b\x32\x05.Vels\x12\x13\n\x03img\x18\x0b \x01(\x0b\x32\x06.Image\"\x16\n\x03Res\x12\x0f\n\x07success\x18\x15 \x01(\x08\x32&\n\tMyService\x12\x19\n\x08sendData\x12\x05.Data\x1a\x04.Res\"\x00\x62\x06proto3')



_IMAGE = DESCRIPTOR.message_types_by_name['Image']
_VELS = DESCRIPTOR.message_types_by_name['Vels']
_DATA = DESCRIPTOR.message_types_by_name['Data']
_RES = DESCRIPTOR.message_types_by_name['Res']
Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

Vels = _reflection.GeneratedProtocolMessageType('Vels', (_message.Message,), {
  'DESCRIPTOR' : _VELS,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:Vels)
  })
_sym_db.RegisterMessage(Vels)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)

Res = _reflection.GeneratedProtocolMessageType('Res', (_message.Message,), {
  'DESCRIPTOR' : _RES,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:Res)
  })
_sym_db.RegisterMessage(Res)

_MYSERVICE = DESCRIPTOR.services_by_name['MyService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGE._serialized_start=14
  _IMAGE._serialized_end=66
  _VELS._serialized_start=68
  _VELS._serialized_end=100
  _DATA._serialized_start=102
  _DATA._serialized_end=147
  _RES._serialized_start=149
  _RES._serialized_end=171
  _MYSERVICE._serialized_start=173
  _MYSERVICE._serialized_end=211
# @@protoc_insertion_point(module_scope)
